---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=myaccidentalert&var-version=1.0.0-SNAPSHOT"
  labels:
    provider: "fabric8"
    project: "myaccidentalert"
    version: "1.0.0-SNAPSHOT"
    group: "org.redhat.demo"
  name: "myaccidentalert"
spec:
  replicas: 1
  selector:
    project: "myaccidentalert"
    provider: "fabric8"
    group: "org.redhat.demo"
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: "Rolling"
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: "img/icons/camel.svg"
        fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=myaccidentalert&var-version=1.0.0-SNAPSHOT"
      labels:
        provider: "fabric8"
        project: "myaccidentalert"
        version: "1.0.0-SNAPSHOT"
        group: "org.redhat.demo"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "JAVA_APP_DIR"
          value: "/deployments"
        image: "myaccidentalert:latest"
        imagePullPolicy: "Always"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 180
        name: "spring-boot"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: "1.0"
          requests:
            cpu: "0.2"
        securityContext:
          privileged: false
  triggers:
  - type: "ConfigChange"
  - imageChangeParams:
      automatic: true
      containerNames:
      - "spring-boot"
      from:
        kind: "ImageStreamTag"
        name: "myaccidentalert:latest"
    type: "ImageChange"
